question_data = [
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Bulls are attracted to the color red.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category":
     "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Scotland voted to become an independent country during the referendum from September 2014.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Slovakia is a member of European Union-",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science & Nature",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Igneous rocks are formed by excessive heat and pressure.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature",
     "type": "boolean", "difficulty":
     "easy", "question": "An Astronomical Unit is the distance between Earth and the Moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Psychology is the science of behavior and mind.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science & Nature",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Time on Computers is measured via the EPOX System.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linux was first created as an alternative to Windows XP.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Peyton Manning retired after winning Super Bowl XLIX.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Roger Federer is a famous soccer player.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports",
     "type": "boolean",
     "difficulty": "easy",
     "question": "There are a total of 20 races in Formula One 2016 season.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
